# Generated by Django 3.2 on 2022-02-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answerd',
            new_name='answered',
        ),
    ]
